// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GroupTeam.Repository.Models;

public partial class Account
{
    public string Email { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public DateTime? Birthday { get; set; }

    public string Status { get; set; }

    public int? RoleId { get; set; }
}