// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GroupTeam.Repository.Models;

public partial class GroupTeam
{
    public int GroupId { get; set; }

    public string GroupName { get; set; }

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();
}