// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GroupTeam.Repository.Models;

public partial class Team
{
    public int Id { get; set; }

    public string TeamName { get; set; }

    public int Point { get; set; }

    public int? GroupId { get; set; }

    public int Position { get; set; }

    public virtual GroupTeam Group { get; set; }
}