// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PantherPetManagement_CuongCla.Repositories.Models;

public partial class PantherProfile
{
    public int PantherProfileId { get; set; }

    [Required(ErrorMessage = "PantherTypeId is required")]
    public int PantherTypeId { get; set; }

    [Required(ErrorMessage = "PantherName is required")]
    [MinLength(4, ErrorMessage = "PantherName must be at least 4 characters")]
    [RegularExpression(@"^(?:[A-Z][a-z0-9]*)(?: [A-Z][a-z0-9]*)*$",
        ErrorMessage = "PantherName must start each word with a capital letter and contain no special characters (#, @, &, (, ))")]
    public string PantherName { get; set; }

    [Required(ErrorMessage = "Weight is required")]
    [Range(90.00000000000001, float.MaxValue, ErrorMessage = "Weight must be greater than 90")]
    public decimal? Weight { get; set; }

    [Required(ErrorMessage = "Characteristics is required")]
    public string Characteristics { get; set; }

    [Required(ErrorMessage = "Warning is required")]
    public string Warning { get; set; }

    [Required(ErrorMessage = "ModifiedDate is required")]
    public DateTime? ModifiedDate { get; set; }

    public virtual PantherType PantherType { get; set; }
}