// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Medicine_CuongCla.Repositories.Models;

public partial class MedicineInformation
{
    [Required(ErrorMessage = "Medicine ID is required")]
    [Display(Name = "Medicine ID")]
    public string MedicineId { get; set; }

    [Required(ErrorMessage = "Medicine Name is required")]
    [Display(Name = "Medicine Name")]
    public string MedicineName { get; set; }

    [Required(ErrorMessage = "Active Ingredients is required")]
    [MinLength(11, ErrorMessage = "Active Ingredients must be greater than 10 characters")]
    [RegularExpression(@"^([A-Z0-9][a-zA-Z]*\s*)+$", 
        ErrorMessage = "Each word of Active Ingredients must begin with a capital letter or a number (0-9). The value is not allowed to contain special characters.")]
    [Display(Name = "Active Ingredients")]
    public string ActiveIngredients { get; set; }

    [Required(ErrorMessage = "Expiration Date is required")]
    [Display(Name = "Expiration Date")]
    public string ExpirationDate { get; set; }

    [Required(ErrorMessage = "Dosage Form is required")]
    [Display(Name = "Dosage Form")]
    public string DosageForm { get; set; }

    [Required(ErrorMessage = "Warnings And Precautions is required")]
    [Display(Name = "Warnings And Precautions")]
    public string WarningsAndPrecautions { get; set; }

    [Required(ErrorMessage = "Manufacturer ID is required")]
    [Display(Name = "Manufacturer ID")]
    public string ManufacturerId { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }
}