// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LionPetManagement.Repositories.Models;

public partial class LionProfile
{
    public int LionProfileId { get; set; }

    [Required(ErrorMessage = "LionTypeId is required")]
    public int LionTypeId { get; set; }

    [Required(ErrorMessage = "LionName is required")]
    [MinLength(4, ErrorMessage = "LionName must be at least 4 characters")]
    [RegularExpression(@"^(?:[A-Z][a-z]*)(?: [A-Z][a-z]*)*$", 
        ErrorMessage = "LionName must start each word with a capital letter and contain no special characters (#, @, &, (, ))")]
    public string LionName { get; set; }

    [Required(ErrorMessage = "Weight is required")]
    [Range(30.01, double.MaxValue, ErrorMessage = "Weight must be greater than 30")]
    public double Weight { get; set; }

    [Required(ErrorMessage = "Characteristics is required")]
    public string Characteristics { get; set; }

    [Required(ErrorMessage = "Warning is required")]
    public string Warning { get; set; }

    [Required(ErrorMessage = "ModifiedDate is required")]
    public DateTime ModifiedDate { get; set; }

    public virtual LionType LionType { get; set; }
}