// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PRN22_OILPainting.Repository.Models;

public partial class OilPaintingArt
{
    public int OilPaintingArtId { get; set; }

    [Required(ErrorMessage = "ArtTitle is required")]
    [StringLength(100, MinimumLength = 5, ErrorMessage = "ArtTitle must be greater than 4 characters and each word must begin with capital letter")]
    [RegularExpression(@"^([A-Z][a-zA-Z0-9@$&,.()\s]*\s*)+$", ErrorMessage = "Each word of the ArtTitle must begin with the capital letter")]
    public string ArtTitle { get; set; }

    [Required(ErrorMessage = "OilPaintingArtLocation is required")]
    public string OilPaintingArtLocation { get; set; }

    [Required(ErrorMessage = "OilPaintingArtStyle is required")]
    public string OilPaintingArtStyle { get; set; }

    [Required(ErrorMessage = "Artist is required")]
    public string Artist { get; set; }

    [Required(ErrorMessage = "NotablFeatures is required")]
    public string NotablFeatures { get; set; }

    [Required(ErrorMessage = "PriceOfOilPaintingArt is required")]
    public decimal? PriceOfOilPaintingArt { get; set; }

    [Required(ErrorMessage = "StoreQuantity is required")]
    [Range(0, 50, ErrorMessage = "StoreQuantity must be between 0 and 50")]
    public int? StoreQuantity { get; set; }

    public DateTime? CreatedDate { get; set; }

    [Required(ErrorMessage = "SupplierId is required")]
    public string SupplierId { get; set; }

    public virtual SupplierCompany Supplier { get; set; }
}