// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN22_OILPainting.Repository.Models;

public partial class SupplierCompany
{
    public string SupplierId { get; set; }

    public string CompanyName { get; set; }

    public string CompanyTypeDescription { get; set; }

    public int? IsActive { get; set; }

    public virtual ICollection<OilPaintingArt> OilPaintingArts { get; set; } = new List<OilPaintingArt>();
}