// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN22_OILPainting.Repository.Models;

public partial class SystemAccount
{
    public int AccountId { get; set; }

    public string AccountPassword { get; set; }

    public string AccountFullName { get; set; }

    public string AccountEmail { get; set; }

    public int? Role { get; set; }
}