// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SupermarketparkingManagement_CuongCla.Repositories.Models;

public partial class ParkingRecord
{
    public int RecordId { get; set; }

    public string VehiclePlate { get; set; }

    public int? VehicleTypeId { get; set; }

    public DateTime CheckInTime { get; set; }

    public DateTime? CheckOutTime { get; set; }

    public string ParkingSlot { get; set; }

    public decimal? FeePaid { get; set; }

    public virtual VehicleType VehicleType { get; set; }
}