// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SupermarketparkingManagement_CuongCla.Repositories.Models;

public partial class SystemAccount
{
    public int AccountId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? Role { get; set; }

    public bool? IsActive { get; set; }
}